# Configuración de Jupyter Book
title: "Análisis de la Demanda de Servicios de Salud"
author: "Jose Javier Mercado Reyes"
logo: ""
html:
  extra_scripts:
    - https://cdn.plot.ly/plotly-latest.min.js

execute:
  timeout: -1  # Deshabilita el límite de tiempo
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
execute:
  execute_notebooks: "auto"